### ISSUE TITLE
get the query of user from paper-search-bar

### ISSUE THREAD

**Issue by rafaelleru** [Collaborne/paper-search#14]
I'm using paper search bar but I can't obtain the query that user wants to search by:
```
paper-searc-element.query
```

and in API I dont understand how to get this.

**Comment by ronnyroeller** [comment]
@rafaelleru - Not sure if I fully understand your question... But have a look to the demo: https://github.com/Collaborne/paper-search/blob/master/demo/paper-search-panel.html#L22

**Comment by rafaelleru** [comment]
Yes I look the demo and in my code works fine, but when I try to change 
```
   scope.search = function() {
    alert("searching...");
    };
```
for:

``` 
scope.search = function() {
    alert(scope.query);;
};
```

I get empty alert, and I can't find a way to get the user input from ```scope```

**Comment by ronnyroeller** [comment]
I extended the demo to show how to access the `query` property: https://github.com/Collaborne/paper-search/commit/c422be4b16d9ebd1232d14b03c11ea53880c3fe0

In case you use `<paper-search-panel>` (instead of just `<paper-search-bar>`): Please be aware that the property is called `search` (not `query`) -> https://github.com/Collaborne/paper-search/blob/master/demo/paper-search-panel.html#L22
